spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/giga-guide-db
    username: postgres
    password: 1234
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8084