spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/giga-guide-db
    username: postgres
    password: 1234
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8084
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 30m