name: Deploy to Yandex Cloud

on:
  push:
    branches: [main]  # Только push в main

env:
  SSH_HOST: ${{ secrets.YC_SSH_HOST }}
  SSH_USER: ${{ secrets.YC_SSH_USER }}
  REPO: github.com/LatinMapsLives/GigaGuide
  APP_DIR: gigaguide

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🔐 Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.YC_SSH_PRIVATE_KEY }}

      - name: 🚀 Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
            set -e

            echo "📁 Переключаемся в домашнюю директорию"
            cd /home/$USER

            echo "🧹 Удаляем старый проект (если есть)"
            rm -rf $APP_DIR

            echo "⬇️ Клонируем репозиторий"
            git clone https://${REPO} $APP_DIR

            echo "📂 Переход в папку с docker-compose.yml"
            cd $APP_DIR/application/backend/docker-compose

            echo "🔧 Проверка docker compose"
            if ! docker compose version &>/dev/null; then
              echo "🛠 Установка Docker Compose plugin"
              DOCKER_COMPOSE_VERSION="v2.24.6"
              sudo mkdir -p /usr/local/lib/docker/cli-plugins
              curl -SL https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-linux-x86_64 -o docker-compose
              sudo mv docker-compose /usr/local/lib/docker/cli-plugins/docker-compose
              sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
            fi

            echo "⚙️ Сборка и запуск"
            docker compose down
            docker compose up -d --build --remove-orphans

            echo "✅ Деплой завершён"
          EOF
